# Blueprint
SkipGAT:
    num: 2  # Number of Dynamic and Aggregator Block pairs

    # -----------------------------------------
    # Pair 0
    DynamicBlock0:
        distributor:
            - 0
            - 0
        ParallelGNN:
            Model0:
                model: PyGAT
                order:
                    - 0
                layers: 2
                activation:
                    name: LeakyReLU
                    negative_slope: 0.2

                layer0:
                    in_channels: 64
                    out_channels: 32
                    concat: True
                    heads: 5

                layer1:
                    in_channels: 160
                    out_channels: 32
                    concat: True
                    heads: 1

        ParallelMLP:
            Model0:
                model: PyMLP
                order:
                    - 1
                layers: 1
                activation:
                  name: ReLU

                layer0:
                  in_features: 64
                  out_features: 32


    AggregatorBlock0:
        distributor:
            -
                - 0
                - 1

        ParallelAgg:
            Agg0:
                agg: Concat
                order:
                    - 0

    # -----------------------------------------
    # Pair 1
    DynamicBlock1:
        distributor:
            - 0
        ParallelMLP:
            Model0:
              model: PyMLP
              order:
                  - 0
              layers: 1
              activation:
                name: LeakyReLU
                negative_slope: 0.2

              layer0:
                in_features: 64
                out_features:

    AggregatorBlock1:
        distributor:
            -
                - 0
        ParallelAgg:
            Agg0:
                agg: Pass
                order:
                    - 0
