# Blueprint
DGM:
    num: 2  # Number of Dynamic and Aggregator Block pairs

    # -----------------------------------------
    # First block
    DynamicBlock0:
        distributor:
            - 0
            - 0
        ParallelMLP:
            Model0:
                model: PyCDGM
                order:
                    - 0
                layers: 4
                activation:
                    name: ReLU
                layer0:
                    in_features:
                    out_features: 256
                layer1:
                    in_features: 256
                    out_features: 128
                layer2:
                    in_features: 128
                    out_features: 64

                # Layer will be used for GNN
                layer3:
                    in_features: 392
                    out_features: 128

            Model1:
                model: PyPass
                order:
                    - 1


    AggregatorBlock0:
        distributor:
            -
                - 0
        ParallelAgg:
            Agg0:
                agg: Pass
                order:
                    - 0

    # -----------------------------------------
    # Second block
    DynamicBlock1:
        distributor:
            - 0

        ParallelMLP:
            Model0:
                model: PyCDGM
                order:
                    - 0
                layers: 4
                activation:
                    name: ReLU
                layer0:
                    in_features:
                    out_features: 64
                layer1:
                    in_features: 64
                    out_features: 32
                layer2:
                    in_features: 32
                    out_features: 16

                # Layer will be used for GNN
                layer3:
                    in_features: 128
                    out_features: 10


    AggregatorBlock1:
        distributor:
            -   - 0
        ParallelAgg:
            Agg0:
                agg: Pass
                order:
                    - 0