# Blueprint
MLP:
    num: 1  # Number of Dynamic and Aggregator Block pairs

    # -----------------------------------------
    # Pair 0
    DynamicBlock0:
        distributor:
            - 0
        ParallelMLP:
            Model0:
                model: PyMLP
                order:
                    - 0
                layers: 1
                activation:
                  name: ReLU

                layer0:
                  in_features: 64
                  out_features:

    AggregatorBlock0:
        distributor:
            -
                - 0
        ParallelAgg:
            Agg0:
                agg: Pass
                order:
                    - 0
