# Blueprint
GCN:
    DynamicBlock0:
        distributor:
        ParallelGNN:
            Model0:
                model: PyPass
                order:
                layers: 1
                layer0:
                    in_features:
                    out_features:

    AggregatorBlock0:
        distributor:
            -   - 0
                - 1
                - 2
                - 3
        ParallelAgg:
            Agg0:
                agg: Concat
                order:
                    - 0

    DynamicBlock1:
        distributor:

        ParallelGNN:
            Model0:
                model: PyGCN
                order:
                    - 0
                layers: 2
                activation:
                    name: ReLU

                layer0:
                    in_channels:
                    out_channels: 64

                layer1:
                    in_channels: 64
                    out_channels: 32

    AggregatorBlock1:
        distributor:
            -   - 0
        ParallelAgg:
            Agg0:
                agg: Pass
                order:
                    - 0


    DynamicBlock2:
        distributor:
            - 0
        ParallelMLP:
            Model0:
                model: PyMLP
                order:
                    - 0
                layers: 1
                activation:
                    name: Identity

                layer0:
                    in_features: 32
                    out_features:


    AggregatorBlock2:
        distributor:
            -   - 0
        ParallelAgg:
            Agg0:
                agg: Pass
                order:
                    - 0