# Blueprint
DGM:
    num: 2  # Number of Dynamic and Aggregator Block pairs

    # -----------------------------------------
    # Pair 0
    DynamicBlock0:
        distributor:
            - 0
        ParallelMLP:
            Model0:
                model: PyMLP
                order:
                layers: 2
                activation:
                    name: ReLU

                layer0:
                    in_features:
                    out_features: 32

                layer1:
                    in_features: 32
                    out_features: 16

    AggregatorBlock0:
        distributor:
            -   - 0
        ParallelAgg:
            Agg0:
                agg: Pass
                order:
                    - 0


    # -----------------------------------------
    # First block
    DynamicBlock1:
        distributor:
            - 0
        ParallelMLP:
            Model0:
                model: LGNN
                order:
                    - 0
                layers: 3
                activation:
                    name: ReLU
                layer0:
                    in_features:
                    out_features: 8
                layer1:
                    in_features: 8
                    out_features: 4

                # Layer will be used for GNN
                layer2:
                    in_channels: 16
                    out_channels:
                    K: 3


    AggregatorBlock1:
        distributor:
            -
                - 0
        ParallelAgg:
            Agg0:
                agg: Pass
                order:
                    - 0
