# Blueprint
CNN_Extract:
    num: 2  # Number of Dynamic and Aggregator Block pairs

    # -----------------------------------------
    # Pair 0
    DynamicBlock0:
        distributor:
        ParallelCNN:
#            Model0:
#                model: PyCNN
#                order:
#                layers: 2
#                activation:
#                    name: ReLU
#
#                layer0:
#                    in_channels: 1
#                    out_channels: 6
#                    kernel_size: 3
#
#                layer1:
#                    in_channels: 6
#                    out_channels: 12
#                    kernel_size: 3
#
#                mlp_layer:
#                    out_features: 16

#            Model0:
#                model: ResNet
#                order:
#                layers: 1
#                resnet: 18
#                out_features: 64
#
#                layer0:
#                    pretrained: true

            Model0:
                model: AlexNet
                order:
                layers: 1
                out_features: 64

                layer0:
                    pretrained: true

    AggregatorBlock0:
        distributor:
            -
                - 0
        ParallelAgg:
            Agg0:
                agg: Pass
                order:
                    - 0

    # -----------------------------------------
    # Pair 1
    DynamicBlock1:
        distributor:
            - 0
        ParallelMLP:
            Model0:
                model: PyMLPExtract
                order:
                    - 0
                layers: 1
                activation:
                  name: ReLU

                layer0:
                  in_features: 64
                  out_features:

    AggregatorBlock1:
        distributor:
            -
                - 0
        ParallelAgg:
            Agg0:
                agg: Pass
                order:
                    - 0
