# Blueprint
HydraGNN:
    num: 4  # Number of Dynamic and Aggregator Block pairs
    # -----------------------------------------
    # Pair 1
    DynamicBlock0:
        distributor:
            - 0
            - 0
            - 1
            - 1
            - 2
            - 2

        ParallelCNN:
            Model0:
                model: PyCNN
                order:
                    - 0
                layers: 2
                activation:
                    name: LeakyReLU
                    negative_slope: 0.2

                layer0:
                    in_channels: 1
                    out_channels: 6
                    kernel_size: 3

                layer1:
                    in_channels: 6
                    out_channels: 12
                    kernel_size: 3

                mlp_layer:
                    in_features: 48
                    out_features: 16

            Model1:
                model: PyPass
                order:
                    - 1
                layers: 1
                layer0:
                    in_channels:
                    out_channels:

        ParallelMLP:
            Model0:
                model: PyMLP
                order:
                    - 2
                layers: 2
                activation:
                    name: LeakyReLU
                    negative_slope: 0.2

                layer0:
                    in_features:
                    out_features: 32

                layer1:
                    in_features: 32
                    out_features: 16

            Model1:
                model: PyPass
                order:
                    - 3
                layers: 1
                layer0:
                    in_features:
                    out_features:

        ParallelRNN:
            Model0:
                model: PyGRU
                order:
                    - 4
                layers: 1
                layer0:
                    input_size:
                    hidden_size: 8

                fc_layer:
                    in_features: 8
                    out_features: 4

                activation:
                    name: LeakyReLU
                    negative_slope: 0.2


            Model1:
                model: PyPass
                order:
                    - 5
                layers: 1
                layer0:
                    in_features:
                    out_features:

    AggregatorBlock0:
        distributor:
            # For graph learning and feature representation using graph neural networks
            -   - 0
                - 2
                - 4

            # For reconstruction
            -   - 0
                - 1
            -   - 2
                - 3
            -   - 4
                - 5

        ParallelAgg:
            Agg0:
                agg: Concat
                order:
                    - 0

            # Images
            Agg1:
                agg: Merge
                order:
                    - 1
                keyname0: "input"
                keyname1: "target_output"

            # Feature
            Agg2:
                agg: Merge
                order:
                    - 2
                keyname0: "input"
                keyname1: "target_output"


            # Sequence
            Agg3:
                agg: Merge
                order:
                    - 3
                keyname0: "input"
                keyname1: "target_output"

    # -----------------------------------------
    # Pair 2 Graph Learning
    DynamicBlock1:
        distributor:
            - 0
            - 1
            - 2
            - 3

        ParallelMLP:
            Model0:
                model: PyMLP
                order:
                    - 0
                layers: 2
                activation:
                    name: LeakyReLU
                    negative_slope: 0.2
                layer0:
                    in_features:
                    out_features: 16
                layer1:
                    in_features: 16
                    out_features: 8

            Model1:
                model: PyPass
                order:
                    - 1
                    - 2
                    - 3
                layers: 1
                layer0:
                    in_features:
                    out_features:


    AggregatorBlock1:
        distributor:
            # Predicted reconstruction outputs
            -   - 0
                - 1
            -   - 0
                - 2
            -   - 0
                - 3

            # For classification
            -   - 0

        ParallelAgg:
            Agg0:
                agg: Concat
                order:
                    - 0
                    - 1
                    - 2
            Agg1:
                agg: Pass
                order:
                    - 3

    # -----------------------------------------
    # Pair 3 Reconstruction
    DynamicBlock2:
        distributor:
            - 0  # used to reconstruct CNN
            - 1  # used to reconstruct MLP
            - 2  # used to reconsuct RNN
            - 3  # used for classification

        ParallelCNN:
            Model0:
                model: PyUpConv
                order:
                    - 0
                layers: 7
                activation:
                    name: LeakyReLU
                    negative_slope: 0.2

                layer0:  # MLP
                    in_features:
                    out_features: 48
                    channels: 12
                    height: 2
                    width: 2

                layer1:
                    in_channels: 12
                    out_channels: 12
                    kernel_size: 3

                layer2:
                    in_channels: 12
                    out_channels: 6
                    kernel_size: 3

                layer3:
                    in_channels: 6
                    out_channels: 6
                    kernel_size: 3

                layer4:
                    in_channels: 6
                    out_channels: 3
                    kernel_size: 3

                layer5:
                    in_channels: 3
                    out_channels: 3
                    kernel_size: 3

                layer6:
                    in_channels: 3
                    out_channels: 1
                    kernel_size: 3

        ParallelMLP:

            # Classification
            Model0:
                model: PyMLP
                order:
                    - 3
                layers: 1
                activation:
                    name: LeakyReLU
                    negative_slope: 0.2
                layer0:
                    in_features:
                    out_features: 10

            Model1:
                model: PyMLP
                order:
                    - 1
                layers: 2
                activation:
                    name: LeakyReLU
                    negative_slope: 0.2
                layer0:
                    in_features:
                    out_features: 32

                layer1:
                    in_features: 32
                    out_features: 196

         # Reconstruct sequential input
        ParallelRNN:
            Model0:
                model: PyDecoderGRU
                order:
                    - 2
                layers: 1
                timesteps: 14
                layer0:
                    input_size:
                    hidden_size: 8

                fc_layer:
                    in_features: 8
                    out_features: 14

                activation:
                    name: Sigmoid



##### HOW TO CALCULATE LOSS

    AggregatorBlock2:
        distributor:
            -   - 0
            -   - 1
            -   - 2
            -   - 3

        ParallelAgg:
            Agg0:
                agg: Pass
                order:
                    - 0
                    - 1
                    - 2
                    - 3
